site_name: Poetry cookiecutter
repo_name: poetry_cookiecutter
copyright: Copyright &copy; 2021 - 2022 Quentin Blampey
theme:
  name: material
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Features:
    - Poetry usage: features/poetry.md
    - Documentation: features/doc.md
    - Testing: features/test.md
    - Code style: features/style.md
    - Deploy on PyPI: features/pypi.md
    - Github actions: features/actions.md
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true